### ISSUE TITLE
Моделирование: Линейный полином

### ISSUE THREAD

**Issue by Maks1mS** [shizand/statapp#33]
![image](https://github.com/shizand/statapp/assets/36362599/24f6f0a5-85e1-4cab-95fb-ca916fd29dfe)

Кроме таблицы еще "Ост. дисперсия" в заголовке

**Comment by MisterMLiL** [comment]
[linearPolinom.txt](https://github.com/shizand/statapp/files/12807035/linearPolinom.txt)
Код

**Comment by Maks1mS** [comment]
https://stackoverflow.com/a/56217960

**Comment by MisterMLiL** [comment]
ммм, mean

**Comment by Maks1mS** [comment]
>Are you sure that the above calculation for MSE is correct? residuals is the sum of squared residuals per numpy's documentation. This means that you need to divide residuals by b.size to get MSE. Right? – 
[gplt](https://stackoverflow.com/users/8517087/gplt)
 [Apr 14, 2021 at 19:28](https://stackoverflow.com/questions/56216327/cant-figure-out-how-to-print-the-least-squares-error/56217960#comment118601538_56217960) 
Yes - and .mean divides by size, as opposed to .sum (or an I misreading your question?) – 
[Itamar Mushkin](https://stackoverflow.com/users/8874696/itamar-mushkin)

**Comment by Maks1mS** [comment]
Возможно еще нужно будет делить на b.size

**Comment by MisterMLiL** [comment]
жалко конечно

**Comment by MisterMLiL** [comment]
Испарвлен #74
