### ISSUE TITLE
Преобразования

### ISSUE THREAD

**Issue by Maks1mS** [shizand/statapp#41]
Из STAT.EXE

> ### 3.1.4. ВКЛЮЧЕНИЕ ПРЕОБРАЗОВАНИЙ
> 
> Это флаг со значениями "YES" или "NO", позволяющий реализовать расширение пакета PREOBR.EXE. При этом над выборочными значениями каждого столбца входного файла возможно осуществить преобразования по следующим функциям (считается, что их набор достаточен для аппроксимации):
> 
> - X^2
> - SIN(x)
> - ARCTG(x)
> - Ln(x), x > 0
> - a + b*x, a,b-CONST
> - X(i)* X(j), j > i
> - X(i)/X(j), j ≠ i, x(j) ≠ 0
> 
> _При повторном подключении преобразований к уже преобразованным данным (временный файл TEMP.REG или DUBLTEMP.REG) осуществима суперпозиция типов преобразований. Подробнее о преобразованиях см. соответствующий раздел._
> 
> Если в текущем МЕНЮ преобразования были включены, то после их реализации Вы опять попадаете в МЕНЮ "Параметры задачи...", но уже "...после преобразований".
> 
> ---
> 
> ### 3.3. ПРЕОБРАЗОВАНИЯ
> 
> #### 3.3.1
> 
> Процедура преобразований реализуется, начиная с **корневого** режима (1-й уровень). В нем возможны функции:
> 
> - Выбрать в исходной матрице столбец для преобразований (переменная x(i) задается по принципу МАСКИ)
> - Задать список непреобразуемых столбцов той же матрицы (маска линейной части постулируемой регрессионной модели)
> - Завершить преобразования и выйти в МЕНЮ "Параметры задачи после преобразований" со значением флага (3.1.4) ="NO".
> 
> #### 3.3.2
> 
> Выбор типа преобразования (2-й уровень) производится посредством меню-функций ранее выбранного аргумента x(i).
> 
> #### 3.3.3
> 
> Для реализации **произведения** и **частного** существует 3-й уровень. В нем в форме маски задается список множителей и делителей соответственно.

**Comment by KaMZeSs** [comment]
Так а вопрос в чем?
Студент, вопрос начинается с вопросительного слова!!!

**Comment by Maks1mS** [comment]
Преобразования
- sin(x)
- cos(x)
- Ln(x)
- exp(x)
