### ISSUE TITLE
Генератор факторов генерирует с большим среднеквадратичным отклонением

### ISSUE THREAD

**Issue by Maks1mS** [shizand/statapp#50]
Везде были заданы параметры 100 100 2

![image](https://github.com/shizand/statapp/assets/36362599/79bc9a63-8a7a-4b6a-8eda-41e2f9c30727)

**Comment by Maks1mS** [comment]
6000 300
300 10

![image](https://github.com/shizand/statapp/assets/36362599/b86a526f-bf10-4ad3-b479-b74d37895b97)

**Comment by MisterMLiL** [comment]
![image](https://github.com/shizand/statapp/assets/99662459/82aef5a7-84a0-42f0-b5b3-6d05f306c5b7)
Скорее всего проблема в генерации коэффициента k, так как в случае k > 1, может получаться 2 - 1/k, то есть в теории до 1.99
Почему увеличение 4 кратное не знаю, возможно проблема метода np.random.normal или метод, который используется выдает не среднеквадратическое отклонение, а разницу между максимальным и минимальным значением

**Comment by Maks1mS** [comment]
Т.к. у нас теперь генерация отделена от UI , то можно теперь проще экспериментировать.
Можно сделать скрипт, который генерирует значения и считает СКО.
