### ISSUE TITLE
Не запускается на ОС Альт (libbz2.so.1.0: cannot open shared object file)

### ISSUE THREAD

**Issue by Maks1mS** [shizand/statapp#61]
```
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
[90012] Failed to execute script '__main__' due to unhandled exception!
```

Проблема в том, что [в ОС Альт отсутствует симлинк libbz2.so.1.0](https://bugzilla.altlinux.org/35320).

Временное "костыльное" решение:
```
# ln -s /lib64/libbz2.so.1.0.8 /lib64/libbz2.so.1.0
```
`1.0.8` - текущая версия пакета.

**Comment by KaMZeSs** [comment]
А почему бы просто не оставить костыль?

**Comment by Maks1mS** [comment]
> А почему бы просто не оставить костыль?

Может потому что для решения этой проблемы нужно от рута делать симлинк?

**Comment by Maks1mS** [comment]
Добавлены пакеты для ОС Альт
https://github.com/shizand/altlinux-specs/releases?q=statapp
