### ISSUE TITLE
Сохранение данных в файл в экспоненциальном формате

### ISSUE THREAD

**Issue by MisterMLiL** [shizand/statapp#76]
6.075170000000000073e+03	3.017860000000000127e+03	2.987389999999999873e+03
6.010050000000000182e+03	3.006619999999999891e+03	2.990340000000000146e+03
5.962529999999999745e+03	2.986019999999999982e+03	3.002679999999999836e+03
5.932840000000000146e+03	2.993409999999999854e+03	3.012510000000000218e+03

![sticker](https://github.com/shizand/statapp/assets/99662459/a66cbff2-3ebe-4227-b54f-7c8e36270886)

**Comment by Maks1mS** [comment]
[numpy.savetxt.html](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html)
![image](https://github.com/shizand/statapp/assets/36362599/cdd9d8e4-3649-4b6e-a910-5a0999fc9468)

**Comment by Maks1mS** [comment]
Закрыто в #79
